let a=3,b=5,sum=a+b,sub=b-a,mul=a*b,div=a/b,mod=a%b;
document.getElementById('sum').innerHTML = 'Sum of '+a+' and '+b+' is '+sum;
document.getElementById('sub').innerHTML = 'Subtracting '+b+' from '+a+' = '+sub;
document.getElementById('mul').innerHTML = 'Product of '+a+' and '+b+' is '+mul;
document.getElementById('div').innerHTML = 'Dividing '+a+'/'+b+'='+div;
document.getElementById('mod').innerHTML = 'modulus of '+a+' and '+b+' is '+mod;
let variable;
document.getElementById('variableDeclaration').innerHTML = 'Value after variable declaration is '+variable;
variable=5;
document.getElementById('variableInitialize').innerHTML = 'Initial Value:'+variable;
variable++;
document.getElementById('variableIncrement').innerHTML = 'Value after increment is:'+variable;
variable+=7;
document.getElementById('variableAddition').innerHTML = 'Value after addition is:'+variable;
variable--;
document.getElementById('variableDecrement').innerHTML = 'Value after decrement is:'+variable;
variable%=3;
document.getElementById('variableRemainder').innerHTML = 'The remainder is:'+variable;
let ticket = 600,numberOfTickets=5,costOfTickets=ticket*numberOfTickets;
document.getElementById('ticket').innerHTML = 'The Cost to buy '+numberOfTickets+' ticket(s) to a movie is '+costOfTickets+'PKR';
let tableNumber = 4,table;
document.getElementById('printTable').innerHTML = 'Table of '+tableNumber;
for (let i = 1; i <= 10 ; i++) {
    table = document.createElement('p');
    table.innerHTML = tableNumber+' x '+i+' = '+tableNumber*i;
    document.getElementById('printTable').appendChild(table);
}
let celsius = 25,fahrenheit=70,celsiusToFahrenheit=(celsius*9/5)+32,fahrenheitToCelsius=(fahrenheit-32)*(5/9);
document.getElementById('cToF').innerHTML = celsius+'<sup>o</sup> is '+celsiusToFahrenheit+'<sup>o</sup>F';
document.getElementById('fToC').innerHTML = fahrenheit+'<sup>o</sup> is '+fahrenheitToCelsius+'<sup>o</sup>C';
let priceOfItems= [650,100],quantityOfItems= [3,7],shippingCharges= 100,totalCostPrice= 0,priceOfItem,quantityOfItem;
for (let i = 0; i < priceOfItems.length; i++) {
    priceOfItem = document.createElement('p');
    priceOfItem.innerHTML = 'Price of Item '+(i+1)+' is '+priceOfItems[i];
    document.getElementById('price').appendChild(priceOfItem);
    quantityOfItem = document.createElement('p');
    quantityOfItem.innerHTML = 'Quantity of Item '+(i+1)+' is '+quantityOfItems[i];
    document.getElementById('quantity').appendChild(quantityOfItem);
    totalCostPrice += priceOfItems[i] * quantityOfItems[i];
}
document.getElementById('total').innerHTML = 'Total Cost Price of Your Order is '+(totalCostPrice+shippingCharges);
let obtainMarks=905,totalMarks=1100,percentage=(obtainMarks/totalMarks)*100;
document.getElementById('totalMark').innerHTML = 'Total Marks:'+totalMarks;
document.getElementById('obtainMarks').innerHTML = 'Obtained Marks:'+obtainMarks;
document.getElementById('percentage').innerHTML = 'Percentage:'+percentage+'%';
let dollar=10,riyal=25,dollarInPakistan=104.80,riyalInPakistan=28,dollarToRupee=dollar*dollarInPakistan,riyalToRupee=riyal*riyalInPakistan,totalCurrency=riyalToRupee+dollarToRupee;
document.getElementById('rupee').innerHTML = 'Currency in PKR:'+totalCurrency;
let num=10;
num = num + 5 * 10 / 2;
document.getElementById('calculator').innerHTML = 'Result:'+(num);
let currentYear = new Date().getFullYear(),birthYear = 2000,age1 = currentYear - birthYear,age2 = age1-1;
document.getElementById('currentYear').innerHTML = 'Current Year:'+currentYear;
document.getElementById('birthYear').innerHTML = 'Birth Year:'+birthYear;
document.getElementById('age1').innerHTML = 'Age 1: '+age1+' Years';
document.getElementById('age2').innerHTML = 'Age 2: '+age2+' Years';
let radiusOfCircle = 20,pi= 3.142,circumference= 2 * pi * radiusOfCircle,area= pi*radiusOfCircle*radiusOfCircle;
document.getElementById('radius').innerHTML = 'Radius of Circle:'+radiusOfCircle;
document.getElementById('circumference').innerHTML = 'Circumference of Circle:'+circumference;
document.getElementById('area').innerHTML = 'Area of Circle:'+area;
let snacks = 'Chocolate chip',currentAge=19,maximumAge= 63,amountOfSnacks=3,totalEatLife=(maximumAge-currentAge)*amountOfSnacks;
document.getElementById('snacks').innerHTML = 'Favourite Snacks:'+snacks;
document.getElementById('currentAge').innerHTML = 'Current Age:'+currentAge;
document.getElementById('maxAge').innerHTML = 'Estimated Age:'+maximumAge;
document.getElementById('amountOfSnacksPerDay').innerHTML = 'Amount of snacks per day:'+amountOfSnacks;
document.getElementById('Snack').innerHTML = 'You will need '+totalEatLife+' '+snacks+' to last you until the ripe old age of '+maximumAge;